### PR TITLE
upgrading Swashbuckle and fixing swagger-ui flaw

### PR DESCRIPTION
**Pull request by brettsam**

### CODE REVIEW

**Comment by danderson00** [comment]
Can you describe the OAuth authentication stuff?

**Comment by brettsam** [comment]
To back things up: App Service Authentication needs a couple of things done uniquely for its login flow. In order to get things to work, I took the swagger implementation and tweaked it. The unfortunate side effect of this is that whenever this file updates, we need to merge those updates with our logic. What you see here is mostly that -- the only place I've changed anything is where the code is wrapped in //<AzureMobile> tags. Those indicate deviations from the original file.

This newest version introduced some new behavior -- like support for multiple auth schemes (you can now use both google and facebook for example). But it coordinates that logic by using the state parameter, which App Service Auth does not pass back to us. So I had to make an extra tweak to get this working.

I'd like to come up with a better model than mucking with this file, but this is the quickest way to get things working with the latest build.

**Comment by danderson00** [comment]
Looks good to me!

**Comment by adrianhall** [comment]
@pvbchak - Can you please merge this before you release the next server release?

**Pull request merged**
