### PR TITLE
Add hook for custom complex entity relationships

### PR DESCRIPTION
**Pull request by migig**
Allows a subclass to call out into a service to perform custom complex entity relationships - i.e. a custom mapping for many:many scenarios.

[Refer to issue here](https://github.com/Azure/azure-mobile-apps-net-server/issues/159).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@migig__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by brettsam** [comment]
Thanks for the contribution @migig! Can you follow the link above to sign the CLA? Then we can start looking into this.

**Comment by migig** [comment]
@brettsam Already did that and it didn't work for me?? :confused: 

Regardless, my sample code was very minimal, just a sample really, so please feel free to hack it apart and use as you see fit. :grinning:

**Comment by azurecla** [comment]
__@migig__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by migig** [comment]
Great it seems to have worked on the second attempt.

**Comment by migig** [comment]
On second thought, those two new map methods are `private`, but they should be `protected virtual` so they can be tested.

**Comment by adrianhall** [comment]
Hi @migig - looks like the only thing this PR does is abstract the Mapper.Map calls to MapDtoToEntity new method calls.  Can you walk me through why this PR is better than the status quo?

**Comment by adrianhall** [comment]
30 day closure with no response.

**Pull request closed without merging**
