### PR TITLE
update Jwt to 5.1.2 and corresponding changes

### PR DESCRIPTION
**Pull request by tofutim**
Attempt to address https://github.com/Azure/azure-mobile-apps-net-server/issues/185 (upgrade to nuget package System.IdentityModel.Tokens.Jwt v5.1.2 which has confusing halfway namespace change to Microsoft.IdentityModel.Tokens...). I have not had a chance to test it, but it does compile. Please advise.

**Notes.**
1. In some cases, there were changes from tokens to keys. I choose symmetrickeys, but I'm not sure, e.g.,

```
-            validationParams.IssuerSigningToken = new BinarySecretSecurityToken(HmacSigningCredentials.ParseKeyString(secretKey));
+            validationParams.IssuerSigningKey = new IdentityModel.Tokens.SymmetricSecurityKey(HmacSigningCredentials.ParseKeyString(secretKey));
```

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tofutim__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@tofutim__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by tofutim** [comment]
I'm not sure exactly how to test. Any help would be much appreciated.

**Comment by pvbchak** [comment]
@tofutim, System.IdentityModel.Tokens.Jwt 5.x nugets are only supported with ASP.NET Core 1.x (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/README.md#usage).

Mobile Apps .Net Server SDK is not supported on ASP.NET Core & so have to revert back to System.IdentityModel.Tokens.Jwt 4.x.

**Pull request closed without merging**
